### ISSUE TITLE
branch spectogram, crash on exit

### ISSUE THREAD

**Issue by rghvdberg** [michaelwillis/dragonfly-reverb#19] opened 2018-03-31 07:17 UTC
```
Starting program: /home/rob/git/dragonfly-reverb/bin/DragonflyReverb 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7f27700 (LWP 8484)]
[New Thread 0x7ffff7ea6700 (LWP 8485)]
[New Thread 0x7ffff1a34700 (LWP 8487)]
[New Thread 0x7ffff1233700 (LWP 8488)]
[Thread 0x7ffff1233700 (LWP 8488) exited]
[Thread 0x7ffff7ea6700 (LWP 8485) exited]
[Thread 0x7ffff7f27700 (LWP 8484) exited]

Thread 4 "Spectrogram" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff1a34700 (LWP 8487)]
0x00007ffff62a7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: Bestand of map bestaat niet.

Thread 4 (Thread 0x7ffff1a34700 (LWP 8487)):
#0  0x00007ffff62a7428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff62a902a in __GI_abort () at abort.c:89
#2  0x00007ffff62e97ea in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff64012c9 "%s") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff62e980e in __GI___libc_fatal (message=message@entry=0x7ffff77c24d8 "FATAL: exception not rethrown\n") at ../sysdeps/posix/libc_fatal.c:185
#4  0x00007ffff77bf030 in unwind_cleanup (reason=<optimized out>, exc=<optimized out>) at unwind.c:105
#5  0x000000000040e507 in DISTRHO::Signal::wait (this=0xb22110) at ../../dpf/distrho/extra/Mutex.hpp:229
#6  0x000000000040d3b8 in Spectrogram::run (this=0xb1f120) at Spectrogram.cpp:100
#7  0x000000000040eb65 in DISTRHO::Thread::_runEntryPoint (this=0xb1f120) at ../../dpf/distrho/extra/Thread.hpp:268
#8  0x000000000040eb9c in DISTRHO::Thread::_entryPoint (userData=0xb1f120) at ../../dpf/distrho/extra/Thread.hpp:280
#9  0x00007ffff77b66ba in start_thread (arg=0x7ffff1a34700) at pthread_create.c:333
#10 0x00007ffff637941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7f298c0 (LWP 8480)):
#0  0x00007ffff636ef47 in ioctl () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007ffff564868c in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#2  0x00007ffff5649607 in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#3  0x00007ffff56497d5 in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#4  0x00007ffff5348b5a in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#5  0x00007ffff5348d0d in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#6  0x00007ffff528372f in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#7  0x00007ffff5283856 in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#8  0x00007ffff5299960 in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#9  0x00007ffff5270d2d in ?? () from /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
#10 0x00007ffff74f3d61 in ?? () from /usr/lib/nvidia-384/libGL.so.1
#11 0x00007ffff74f7ba8 in ?? () from /usr/lib/nvidia-384/libGL.so.1
#12 0x000000000046105d in destroyContext (view=0x91b050) at src/pugl/pugl_x11.c:192
#13 0x000000000046166b in puglDestroy (view=0x91b050) at src/pugl/pugl_x11.c:344
#14 0x0000000000463fa8 in DGL::Window::PrivateData::~PrivateData (this=0x91afd0, __in_chrg=<optimized out>) at src/Window.cpp:261
#15 0x00000000004624c1 in DGL::Window::~Window (this=0x7fffffffddd8, __in_chrg=<optimized out>) at src/Window.cpp:1049
#16 0x0000000000410d54 in DISTRHO::UIExporterWindow::~UIExporterWindow (this=0x7fffffffddd8, __in_chrg=<optimized out>) at ../../dpf/distrho/src/DistrhoUIInternal.hpp:165
#17 0x00000000004112f0 in DISTRHO::UIExporter::~UIExporter (this=0x7fffffffddc0, __in_chrg=<optimized out>) at ../../dpf/distrho/src/DistrhoUIInternal.hpp:219
#18 0x0000000000411a9c in DISTRHO::PluginJack::~PluginJack (this=0x7fffffffdda0, __in_chrg=<optimized out>) at ../../dpf/distrho/src/DistrhoPluginJack.cpp:189
#19 0x000000000040f789 in main () at ../../dpf/distrho/src/DistrhoPluginJack.cpp:588
```

**Comment by davephillips** [comment] 2018-04-02 21:57
Confirmed on Fedora 23 as well.

**Comment by michaelwillis** [comment] 2018-04-06 15:35
@rghvdberg @davephillips This should be fixed on the latest release: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.0.9-pre

**Comment by michaelwillis** [comment] 2018-04-06 18:27
This is still a bug:

```
[New Thread 0x7fffabd13700 (LWP 17903)]
assertion failure: "! isThreadRunning()" in file ../../dpf/distrho/extra/Thread.hpp, line 157

Thread 43 "Spectrogram" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffabd13700 (LWP 17903)]
0x00007fff73bf84df in ?? ()
   from /home/nik/.lv2/DragonflyReverb.lv2/DragonflyReverb_ui.so
(gdb) thread aply all bt
Invalid thread ID: aply all bt
(gdb) thread apply all bt

Thread 43 (Thread 0x7fffabd13700 (LWP 17903)):
#0  0x00007fff73bf84df in ?? ()
   from /home/nik/.lv2/DragonflyReverb.lv2/DragonflyReverb_ui.so
Backtrace stopped: Cannot access memory at address 0x7fffabd12a98
Couldn't get registers: No such process.
(gdb) 

Thread 43 (Thread 0x7fffabd13700 (LWP 17903)):
#0  0x00007fff73bf84df in ?? ()
   from /home/nik/.lv2/DragonflyReverb.lv2/DragonflyReverb_ui.so
Backtrace stopped: Cannot access memory at address 0x7fffabd12a98
Couldn't get registers: No such process.
(gdb) 
```

**Comment by davephillips** [comment] 2018-04-06 18:28
Just to note: I built from the latest git pull today, the standalone still produces the error report on exit.

**Comment by michaelwillis** [comment] 2018-04-08 23:26
This should be fixed with the latest prerelease: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.9.0

**Comment by davephillips** [comment] 2018-04-09 10:33
The issue is resolved here with your latest code. I tested the standalone and the VST in Bitwig, no problems on exit. And the sound is excellent. :) Thanks @michaelwillis and @rghvdberg  for all your work on this very fine software !

**Comment by michaelwillis** [comment] 2018-04-09 14:16
@davephillips Thanks for being so prompt and consistent testing this! I'd love to hear some music that you make with it.

**Closed by michaelwillis** 2018-04-09 14:16 UTC
