### ISSUE TITLE
VST crashes on Reaper

### ISSUE THREAD

**Issue by armandoarmandone** [michaelwillis/dragonfly-reverb#92] opened 2021-01-22 16:08 UTC
I used Dragonfly reverbs for months without any problems. 
It's about 2 weeks that Reaper started to crush every time I add it to a track.
All other plugins works correctly but I can't use anymore neither of these ones.
Apparently, I'm the only one to have this problem because in every forum there wasn't a solution.

I use Windows 10 (64-bit)

**Comment by michaelwillis** [comment] 2021-01-22 16:18
If you haven't already done this, please download [version 3.2.3](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.3) - This release fixed an obscure bug that could cause all manner of havoc. If you are already using 3.2.3 and it crashes Reaper, please let me know.

**Comment by armandoarmandone** [comment] 2021-01-23 17:10
Before and during the first crash I was using 3.2.1 - After that I also tried to download 3.2.3 but the issue still remains

**Comment by aBoredDev** [comment] 2021-02-07 19:44
It also crashes when I add it to a track in Cubase AI 10.5.20.  Tried it with version 3.2.3 of the plugin and it still crashes.  Unfortunately Cubase doesn't give you much of a crash report, only memory dumps as far as I can tell.  Here's what I have though:
```
The application was terminated with an error while executing the following file:
C:\WINDOWS\SYSTEM32\dxgi.dll

If this error persists, please send the following log file to Technical Support:
C:\Users\MyName\Documents\Steinberg\CrashDumps\Cubase AI 10.5.20.179 64bit 2021.2.7 11.31.53.584.dmp
```
`dxgi.dll` is related to DirectX, so maybe it's something to do with graphics?
Here's the exception info from the memory dump (the process was Cubase itself):
```
Exception Code: 0xC0000005
Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
```
If you want the full memory dump file, let me know.  It has my name in a couple of spots so I'm hesitant to just send it out to anyone.

Cubase will only load the VST versions of the plugins because it only supports VST, not LV2.  IDK if that would affect anything

**Comment by michaelwillis** [comment] 2021-02-07 20:00
@armandoarmandone @aBoredDev This likely has something to do with the graphics libraries. I'm working on a prototype of Dragonfly Reverb 4, which doesn't depend on OpenGL. All previous versions use OpenGL and a number of people have reported various related bugs. I'll let you know when an alpha release is available.

**Comment by tionebrr** [comment] 2021-04-13 04:03
I can confirm v3.2.5 insta-crashing Reaper v6.27 on Win10. And it is looking like it is indeed GUI related.
Starred, I would love to hear those reverbs :)

**Comment by wibblemonkey** [comment] 2021-05-30 15:23
I can confirm the same issue. I've tried every release going back to 3.1.2 - they all cause the latest releases of Reaper to crash out with an access violation error in `dxgi.dll`. Any update on a fix for this issue?

**Comment by Amossen** [comment] 2021-06-04 15:39
I can confirm v3.2.3 and v3.2.5 insta-crashing Reaper v6.29 on Win10 (64-bit)

**Comment by aBoredDev** [comment] 2022-04-13 18:54
The update seems to have fixed the crashing issues with Cubase, thanks!

**Closed** 2022-12-28 22:17 UTC

**Comment by tionebrr** [comment] 2022-12-31 12:28
Hey thanks @michaelwillis 
There are other issues but they work ;)
