### ISSUE TITLE
Dragonfly makes hosts crash

### ISSUE THREAD

**Issue by sub26nico** [michaelwillis/dragonfly-reverb#21] opened 2018-04-07 21:20 UTC
I've got issues with Dragonfly-reverb (0.0.9) with many hosts.
Distro: LibraZiK (based on Debian Stretch. 
No problem in Ardour 5.12 (lv2 or vst).
Qtractor crashes when I close the dragonfly-reverb's window (lv2 and vst):
```
*** Error in `qtractor': free(): invalid next size (normal): 0x0000564dde80c850 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f8b42736bfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f8b4273cfc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f8b4273d80e]
/usr/lib/vst/DragonflyReverb-vst.so(+0xdbf2)[0x7f8b12125bf2]
/usr/lib/vst/DragonflyReverb-vst.so(+0xded9)[0x7f8b12125ed9]
/usr/lib/vst/DragonflyReverb-vst.so(+0xc1d5)[0x7f8b121241d5]
/usr/lib/vst/DragonflyReverb-vst.so(+0xc409)[0x7f8b12124409]
/usr/lib/vst/DragonflyReverb-vst.so(+0xffeb)[0x7f8b12127feb]
qtractor(+0x1cf513)[0x564ddb103513]
qtractor(+0x1d0e92)[0x564ddb104e92]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x358)[0x7f8b440c8278]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f8b44080b8c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x261)[0x7f8b44088341]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7f8b4379d9e0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN14QWidgetPrivate12close_helperENS_9CloseModeE+0x2d1)[0x7f8b440c3821]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bb166)[0x7f8b440e2166]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1be243)[0x7f8b440e5243]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f8b44080b8c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x261)[0x7f8b44088341]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7f8b4379d9e0]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processCloseEventEPN29QWindowSystemInterfacePrivate10CloseEventE+0x9c)[0x7f8b43ae2b9c]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x165)[0x7f8b43ae76b5]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xbb)[0x7f8b43ac561b]
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x724c0)[0x7f8b472714c0]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7f8b3f44e7f7]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4aa60)[0x7f8b3f44ea60]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f8b3f44eb0c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f8b437f204f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xfa)[0x7f8b4379b9ca]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QDialog4execEv+0x1b7)[0x7f8b4426f0e7]
qtractor(+0x1cecdd)[0x564ddb102cdd]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x639)[0x7f8b437c95e9]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QAction9triggeredEb+0x42)[0x7f8b4407a1c2]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QAction8activateENS_11ActionEventE+0x110)[0x7f8b4407cbb0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2c51ca)[0x7f8b441ec1ca]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x2cc854)[0x7f8b441f3854]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN5QMenu17mouseReleaseEventEP11QMouseEvent+0x276)[0x7f8b441f4826]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x358)[0x7f8b440c8278]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN5QMenu5eventEP6QEvent+0xa3)[0x7f8b441f6b53]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f8b44080b8c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x111d)[0x7f8b440891fd]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7f8b4379d9e0]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb+0x1dd)[0x7f8b440878ad]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bbd16)[0x7f8b440e2d16]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1be313)[0x7f8b440e5313]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7f8b44080b8c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x261)[0x7f8b44088341]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7f8b4379d9e0]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x743)[0x7f8b43ae5b03]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x135)[0x7f8b43ae7685]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xbb)[0x7f8b43ac561b]
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x724c0)[0x7f8b472714c0]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7f8b3f44e7f7]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4aa60)[0x7f8b3f44ea60]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f8b3f44eb0c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f8b437f204f]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xfa)[0x7f8b4379b9ca]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN5QMenu4execERK6QPointP7QAction+0x6d)[0x7f8b441f131d]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x358)[0x7f8b440c8278]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN6QFrame5eventEP6QEvent+0x1e)[0x7f8b441b0a0e]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent+0x111)[0x7f8b4379d741]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x75)[0x7f8b44080b65]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x13a0)[0x7f8b44089480]
======= Memory map: ========
564ddaf34000-564ddb2d9000 r-xp 00000000 08:23 10228265                   /usr/bin/qtractor
564ddb4d8000-564ddb4f2000 r--p 003a4000 08:23 10228265                   /usr/bin/qtractor
564ddb4f2000-564ddb4f3000 rw-p 003be000 08:23 10228265                   /usr/bin/qtractor
564ddb4f3000-564ddb4f4000 rw-p 00000000 00:00 0 
564ddd34b000-564dde8d3000 rw-p 00000000 00:00 0                          [heap]
7f8afc000000-7f8afc021000 rw-p 00000000 00:00 0 
7f8afc021000-7f8b00000000 ---p 00000000 00:00 0 
7f8b00000000-7f8b00027000 rw-p 00000000 00:00 0 
7f8b00027000-7f8b04000000 ---p 00000000 00:00 0 
7f8b04000000-7f8b04021000 rw-p 00000000 00:00 0 
7f8b04021000-7f8b08000000 ---p 00000000 00:00 0 
7f8b08000000-7f8b08021000 rw-p 00000000 00:00 0 
7f8b08021000-7f8b0c000000 ---p 00000000 00:00 0 
7f8b0c000000-7f8b0c021000 rw-p 00000000 00:00 0 
7f8b0c021000-7f8b10000000 ---p 00000000 00:00 0 
7f8b10a4e000-7f8b10b6c000 rw-s 00000000 00:05 39157807                   /SYSV00000000 (deleted)
7f8b10c8d000-7f8b10c8e000 ---p 00000000 00:00 0 
7f8b10c8e000-7f8b1148e000 rw-p 00000000 00:00 0 
7f8b11c0a000-7f8b11d0a000 rw-s 10f984000 00:06 11927                     /dev/dri/card0
7f8b11d0a000-7f8b11f07000 r-xp 00000000 08:23 10234672                   /usr/lib/x86_64-linux-gnu/libfftw3f.so.3.5.5
7f8b11f07000-7f8b12106000 ---p 001fd000 08:23 10234672                   /usr/lib/x86_64-linux-gnu/libfftw3f.so.3.5.5
7f8b12106000-7f8b12117000 r--p 001fc000 08:23 10234672                   /usr/lib/x86_64-linux-gnu/libfftw3f.so.3.5.5
7f8b12117000-7f8b12118000 rw-p 0020d000 08:23 10234672                   /usr/lib/x86_64-linux-gnu/libfftw3f.so.3.5.5
7f8b12118000-7f8b1234e000 r-xp 00000000 08:23 12322448                   /usr/lib/vst/DragonflyReverb-vst.so
7f8b1234e000-7f8b1254e000 ---p 00236000 08:23 12322448                   /usr/lib/vst/DragonflyReverb-vst.so
7f8b1254e000-7f8b12550000 r--p 00236000 08:23 12322448                   /usr/lib/vst/DragonflyReverb-vst.so
7f8b12550000-7f8b12552000 rw-p 00238000 08:23 12322448                   /usr/lib/vst/DragonflyReverb-vst.so
7f8b12639000-7f8b12abf000 rw-s 00000000 00:05 38993965                   /SYSV00000000 (deleted)
7f8b12abf000-7f8b12d6a000 rw-p 00000000 00:00 0 
7f8b12d6a000-7f8b12d74000 r-xp 00000000 08:23 13636389                   /lib/x86_64-linux-gnu/libnss_files-2.24.so
7f8b12d74000-7f8b12f74000 ---p 0000a000 08:23 13636389                   /lib/x86_64-linux-gnu/libnss_files-2.24.so
7f8b12f74000-7f8b12f75000 r--p 0000a000 08:23 13636389                   /lib/x86_64-linux-gnu/libnss_files-2.24.so
7f8b12f75000-7f8b12f76000 rw-p 0000b000 08:23 13636389                   /lib/x86_64-linux-gnu/libnss_files-2.24.so
7f8b12f76000-7f8b12f7c000 rw-p 00000000 00:00 0 
7f8b12f7c000-7f8b12f87000 r-xp 00000000 08:23 13636391                   /lib/x86_64-linux-gnu/libnss_nis-2.24.so
7f8b12f87000-7f8b13186000 ---p 0000b000 08:23 13636391                   /lib/x86_64-linux-gnu/libnss_nis-2.24.so
7f8b13186000-7f8b13187000 r--p 0000a000 08:23 13636391                   /lib/x86_64-linux-gnu/libnss_nis-2.24.so
7f8b13187000-7f8b13188000 rw-p 0000b000 08:23 13636391                   /lib/x86_64-linux-gnu/libnss_nis-2.24.so
7f8b13188000-7f8b18000000 rw-s 00000000 00:14 3049317                    /dev/shm/jack-1000-0
7f8b18000000-7f8b18021000 rw-p 00000000 00:00 0 
7f8b18021000-7f8b1c000000 ---p 00000000 00:00 0 
7f8b1c0b1000-7f8b1c0b2000 ---p 00000000 00:00 0 
7f8b1c0b2000-7f8b1c8b2000 rw-p 00000000 00:00 0 
7f8b1c8b2000-7f8b1c8b3000 ---p 00000000 00:00 0 
7f8b1c8b3000-7f8b1d0b3000 rw-p 00000000 00:00 0 
7f8b1d0b3000-7f8b1d0b4000 ---p 00000000 00:00 0 
7f8b1d0b4000-7f8b1d8b4000 rw-p 00000000 00:00 0 
7f8b1d8b4000-7f8b1d8c8000 r-xp 00000000 08:23 13636386                   /lib/x86_64-linux-gnu/libnsl-2.24.so
7f8b1d8c8000-7f8b1dac8000 ---p 00014000 08:23 13636386                   /lib/x86_64-linux-gnu/libnsl-2.24.so
7f8b1dac8000-7f8b1dac9000 r--p 00014000 08:23 13636386                   /lib/x86_64-linux-gnu/libnsl-2.24.so
7f8b1dac9000-7f8b1daca000 rw-p 00015000 08:23 13636386                   /lib/x86_64-linux-gnu/libnsl-2.24.so
7f8b1daca000-7f8b1dacc000 rw-p 00000000 00:00 0 
7f8b1dacc000-7f8b1dad1000 r-xp 00000000 08:23 10233682                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f8b1dad1000-7f8b1dcd0000 ---p 00005000 08:23 10233682                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f8b1dcd0000-7f8b1dcd1000 r--p 00004000 08:23 10233682                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f8b1dcd1000-7f8b1dcd2000 rw-p 00005000 08:23 10233682                   /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f8b1dcd2000-7f8b1dcda000 r-xp 00000000 08:23 13632151                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f8b1dcda000-7f8b1deda000 ---p 00008000 08:23 13632151                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f8b1deda000-7f8b1dedb000 r--p 00008000 08:23 13632151                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f8b1dedb000-7f8b1dedc000 rw-p 00009000 08:23 13632151                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f8b1dedc000-7f8b1dee1000 r-xp 00000000 08:23 10233461                   /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7f8b1dee1000-7f8b1e0e0000 ---p 00005000 08:23 10233461                   /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7f8b1e0e0000-7f8b1e0e1000 r--p 00004000 08:23 10233461                   /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7f8b1e0e1000-7f8b1e0e2000 rw-p 00005000 08:23 10233461                   /usr/lib/x86_64-linux-gnu/libXtst.so.6.1.0
7f8b1e0e2000-7f8b1e0e6000 r-xp 00000000 08:23 13631658                   /lib/x86_64-linux-gnu/libcap.so.2.25
7f8b1e0e6000-7f8b1e2e6000 ---p 00004000 08:23 13631658                   /lib/x86_64-linux-gnu/libcap.so.2.25
7f8b1e2e6000-7f8b1e2e7000 r--p 00004000 08:23 13631658                   /lib/x86_64-linux-gnu/libcap.so.2.25
7f8b1e2e7000-7f8b1e2e8000 rw-p 00005000 08:23 13631658                   /lib/x86_64-linux-gnu/libcap.so.2.25
7f8b1e2e8000-7f8b1e368000 r-xp 00000000 08:23 10881387                   /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
7f8b1e368000-7f8b1e568000 ---p 00080000 08:23 10881387                   /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
7f8b1e568000-7f8b1e56a000 r--p 00080000 08:23 10881387                   /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
7f8b1e56a000-7f8b1e56b000 rw-p 00082000 08:23 10881387                   /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-10.0.so
7f8b1e56b000-7f8b1e5b9000 r-xp 00000000 08:23 10227407                   /usr/lib/x86_64-linux-gnu/libpulse.so.0.20.1
7f8b1e5b9000-7f8b1e7b9000 ---p 0004e000 08:23 10227407                   /usr/lib/x86_64-linux-gnu/libpulse.so.0.20.1
7f8b1e7b9000-7f8b1e7bb000 r--p 0004e000 08:23 10227407                   /usr/lib/x86_64-linux-gnu/libpulse.so.0.20.1
7f8b1e7bb000-7f8b1e7bc000 rw-p 00050000 08:23 10227407                   /usr/lib/x86_64-linux-gnu/libpulse.so.0.20.1
7f8b1e7bc000-7f8b1e7bd000 ---p 00000000 00:00 0 
7f8b1e7bd000-7f8b1efbd000 rw-p 00000000 00:00 0 
7f8b1eff1000-7f8b1eff2000 rw-s 10fa84000 00:06 11927                     /dev/dri/card0
7f8b1eff7000-7f8b1f037000 rw-s 11447a000 00:06 11927                     /dev/dri/card0
7f8b1f037000-7f8b1f038000 rw-s 10f8e8000 00:06 11927                     /dev/dri/card0
7f8b1f038000-7f8b1f039000 rw-s 10f8e7000 00:06 11927                     /dev/dri/card0
7f8b1f039000-7f8b1f03a000 rw-s 10f8e6000 00:06 11927                     /dev/dri/card0
7f8b1f065000-7f8b1f0ec000 rw-s 00000000 00:05 39092272                   /SYSV00000000 (deleted)
7f8b1f0ec000-7f8b1f178000 rw-s 00000000 00:05 39026734                   /SYSV00000000 (deleted)
7f8b1f178000-7f8b1f1b0000 r-xp 00000000 08:23 10243089                   /usr/lib/x86_64-linux-gnu/s2tc/libtxc_dxtn.so
7f8b1f1b0000-7f8b1f3b0000 ---p 00038000 08:23 10243089                   /usr/lib/x86_64-linux-gnu/s2tc/libtxc_dxtn.so
7f8b1f3b0000-7f8b1f3b1000 r--p 00038000 08:23 10243089                   /usr/lib/x86_64-linux-gnu/s2tc/libtxc_dxtn.so
7f8b1f3b1000-7f8b1f3b2000 rw-p 00039000 08:23 10243089                   /usr/lib/x86_64-linux-gnu/s2tc/libtxc_dxtn.so
7f8b1f3b2000-7f8b1f3b3000 ---p 00000000 00:00 0 
7f8b1f3b3000-7f8b1fbb3000 rw-p 00000000 00:00 0 
7f8b1fbb3000-7f8b1fbd5000 r-xp 00000000 08:23 13633329                   /lib/x86_64-linux-gnu/libncurses.so.5.9
7f8b1fbd5000-7f8b1fdd4000 ---p 00022000 08:23 13633329                   /lib/x86_64-linux-gnu/libncurses.so.5.9
7f8b1fdd4000-7f8b1fdd5000 r--p 00021000 08:23 13633329                   /lib/x86_64-linux-gnu/libncurses.so.5.9
7f8b1fdd5000-7f8b1fdd6000 rw-p 00022000 08:23 13633329                   /lib/x86_64-linux-gnu/libncurses.so.5.9
7f8b1fdd6000-7f8b1fdfc000 r-xp 00000000 08:23 13631603                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f8b1fdfc000-7f8b1fffb000 ---p 00026000 08:23 13631603                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f8b1fffb000-7f8b1ffff000 r--p 00025000 08:23 13631603                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f8b1ffff000-7f8b20000000 rw-p 00029000 08:23 13631603                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f8b20000000-7f8b20021000 rw-p 00000000 00:00 0 
7f8b20021000-7f8b24000000 ---p 00000000 00:00 0 
7f8b24004000-7f8b24007000 rw-s 10fd3f000 00:06 11927                     /dev/dri/card0
7f8b2400f000-7f8b24016000 r-xp 00000000 08:23 13636387                   /lib/x86_64-linux-gnu/libnss_compat-2.24.so
7f8b24016000-7f8b24215000 ---p 00007000 08:23 13636387                   /lib/x86_64-linux-gnu/libnss_compat-2.24.so
7f8b24215000-7f8b24216000 r--p 00006000 08:23 13636387                   /lib/x86_64-linux-gnu/libnss_compat-2.24.so
7f8b24216000-7f8b24217000 rw-p 00007000 08:23 13636387                   /lib/x86_64-linux-gnu/libnss_compat-2.24.so
7f8b24217000-7f8b24248000 r-xp 00000000 08:23 10234290                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.55
7f8b24248000-7f8b24448000 ---p 00031000 08:23 10234290                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.55
7f8b24448000-7f8b2444a000 r--p 00031000 08:23 10234290                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.55
7f8b2444a000-7f8b2444b000 rw-p 00033000 08:23 10234290                   /usr/lib/x86_64-linux-gnu/libedit.so.2.0.55
7f8b2444b000-7f8b2444f000 rw-p 00000000 00:00 0 
7f8b2444f000-7f8b26d17000 r-xp 00000000 08:23 10238286                   /usr/lib/x86_64-linux-gnu/libLLVM-3.9.so.1
7f8b26d17000-7f8b27006000 r--p 028c7000 08:23 10238286                   /usr/lib/x86_64-linux-gnu/libLLVM-3.9.so.1
7f8b27006000-7f8b2702b000 rw-p 02bb6000 08:23 10238286                   /usr/lib/x86_64-linux-gnu/libLLVM-3.9.so.1
7f8b2702b000-7f8b2706f000 rw-p 00000000 00:00 0 
7f8b2706f000-7f8b27086000 r-xp 00000000 08:23 10228524                   /usr/lib/x86_64-linux-gnu/libelf-0.168.so
7f8b27086000-7f8b27285000 ---p 00017000 08:23 10228524                   /usr/lib/x86_64-linux-gnu/libelf-0.168.so
7f8b27285000-7f8b27286000 r--p 00016000 08:23 10228524                   /usr/lib/x86_64-linux-gnu/libelf-0.168.so
7f8b27286000-7f8b27287000 rw-p 00017000 08:23 10228524                   /usr/lib/x86_64-linux-gnu/libelf-0.168.so
7f8b27287000-7f8b27bc3000 r-xp 00000000 08:23 11679306                   /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
7f8b27bc3000-7f8b27dc2000 ---p 0093c000 08:23 11679306                   /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
7f8b27dc2000-7f8b27dfd000 r--p 0093b000 08:23 11679306                   /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
7f8b27dfd000-7f8b27e09000 rw-p 00976000 08:23 11679306                   /usr/lib/x86_64-linux-gnu/dri/r600_dri.so
7f8b27e09000-7f8b28000000 rw-p 00000000 00:00 0 
7f8b28000000-7f8b28021000 rw-p 00000000 00:00 0 
7f8b28021000-7f8b2c000000 ---p 00000000 00:00 0 
7f8b2c005000-7f8b2c006000 rw-p 00000000 00:00 0 
7f8b2c006000-7f8b2c007000 rw-s 10f855000 00:06 11927                     /dev/dri/card0
7f8b2c007000-7f8b2c008000 rw-s 10f854000 00:06 11927                     /dev/dri/card0
7f8b2c008000-7f8b2c00c000 rw-s 10f850000 00:06 11927                     /dev/dri/card0
7f8b2c00c000-7f8b2c01c000 rw-s 10f94b000 00:06 11927                     /dev/dri/card0
7f8b2c01c000-7f8b2c02c000 rw-s 10f972000 00:06 11927                     /dev/dri/card0
7f8b2c02c000-7f8b2c02d000 rw-s 10f96e000 00:06 11927                     /dev/dri/card0
7f8b2c02d000-7f8b2c03d000 rw-s 10f95e000 00:06 11927                     /dev/dri/card0
7f8b2c03d000-7f8b2c03e000 ---p 00000000 00:00 0 
7f8b2c03e000-7f8b2c0be000 rw-p 00000000 00:00 0 
7f8b2c0be000-7f8b2c0bf000 ---p 00000000 00:00 0 
7f8b2c0bf000-7f8b2c13f000 rw-p 00000000 00:00 0 
7f8b2c13f000-7f8b2c140000 ---p 00000000 00:00 0 
7f8b2c140000-7f8b2c1c0000 rw-p 00000000 00:00 0 
7f8b2c1c0000-7f8b2c1c9000 r-xp 00000000 08:23 10238018                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f8b2c1c9000-7f8b2c3c8000 ---p 00009000 08:23 10238018                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f8b2c3c8000-7f8b2c3c9000 r--p 00008000 08:23 10238018                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f8b2c3c9000-7f8b2c3ca000 rw-p 00009000 08:23 10238018                   /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
7f8b2c3ca000-7f8b2c3d5000 r-xp 00000000 08:23 10238023                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f8b2c3d5000-7f8b2c5d4000 ---p 0000b000 08:23 10238023                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f8b2c5d4000-7f8b2c5d5000 r--p 0000a000 08:23 10238023                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f8b2c5d5000-7f8b2c5d6000 rw-p 0000b000 08:23 10238023                   /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
7f8b2c5d6000-7f8b2c5dd000 r-xp 00000000 08:23 10238020                   /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7f8b2c5dd000-7f8b2c7dc000 ---p 00007000 08:23 10238020                   /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
7f8b2c7dc000-7f8b2c7dd000 r--p 00006000 08:23 10238020                   /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0Abandon

```

**Comment by sub26nico** [comment] 2018-04-07 21:29
With reaper native linux, reaper crashes when I load the (VST)plugin : 
```
assertion failure: "! isThreadRunning()" in file ../../dpf/distrho/extra/Thread.hpp, line 157
segment fault
```
If I try to load dragonfly with carla-vst, same issue. No problem with dragonfly lv2 in Carla-vst.
With Carla standalone application, Carla crashes when I close the UI (vst ). With lv2 version,
it works fine.

**Comment by michaelwillis** [comment] 2018-04-07 22:57
Understood, I'm trying to determine the cause of this bug.

**Comment by michaelwillis** [comment] 2018-04-08 23:26
This should be fixed in the new prerelease: https://github.com/michaelwillis/dragonfly-reverb/releases/tag/0.9.0

**Closed by michaelwillis** 2018-04-08 23:26 UTC

**Comment by sub26nico** [comment] 2018-05-18 17:27
You can hear it : https://exode.me/videos/watch/a0800e94-84a9-45bb-afb7-95f5c88dca8d

**Comment by michaelwillis** [comment] 2018-05-18 17:40
@sub26nico Ha, this appeared in my email as "Dragonfly makes hosts crash". I thought "Oh no! Didn't I already fix that?"

Thanks so much for sharing the video, it is great fun to listen to people using this plugin. What preset did you pick? Or did you dial in your own settings?

**Comment by sub26nico** [comment] 2018-05-18 18:26
@michaelwillis , sorry to had afraid you, I didn't know how to contact you.
But I see you are on the IRC channel of Ardour, I'll know where to find you.
I've used the 'bright room' preset (tweaked a little bit ) on the first track of Luppp (the first guitar arpeggios) and 'medium clear hall' in the mix in Ardour in the 'snare' track.

**Comment by michaelwillis** [comment] 2018-05-18 19:29
@sub26nico There is no need to be sorry! I listened to the whole thing waiting for the crash, and then it finished. The whole time I thought it sounded great, but only after did I realize that this was simply a reply on the issue 😆
