### ISSUE TITLE
Cockos Reaper (x64) crashes when adding any of the reverb plugins

### ISSUE THREAD

**Issue by alexcaragia** [michaelwillis/dragonfly-reverb#72] opened 2020-04-25 10:49 UTC
I have Reaper x64 on two laptops: 
• One runs on a Core i3, 4GB RAM, Nvidia GT920m
• The other runs on a Core i7, 16GB RAM, Nvidia GTX1650
Both on Win10 64bit.
On the i3 one all the plugins work just fine, had no problems with them at all, but when I switched to the i7 laptop, the moment I select one of the reverb plugins to load, the Reaper instance crashes. Do you know what could cause such issue?

**Comment by michaelwillis** [comment] 2020-04-25 21:54
This is probably the same issue as #69. Does the i7 laptop happen to have an option of using onboard Intel graphics hardware? Dragonfly Reverb has a bug that crashes for some people, it seems to be related to nvidia hardware. More than one person has reported being able to work around the bug by switching to the Intel graphics hardware.

**Comment by alexcaragia** [comment] 2020-04-26 08:34
I thought about issue #69 , too, I was trying to find how to use the onboard graphics card for the plugin only, but I guess I'll have to run the whole Reaper instance using the integrated graphics.

**Comment by michaelwillis** [comment] 2020-04-26 13:04
@alexcaragia I'm glad that you found a way to make it work. I really hope that I can find a better solution to the bug.

**Comment by alexcaragia** [comment] 2020-04-26 19:55
Good luck, man, I am really glad I can use your plugins, they are my go to reverbs for guitar and other instruments amongst other paid & free products.

**Comment by michaelwillis** [comment] 2020-04-27 00:07
Good stuff. I'm closing this since you found a way to work around the problem and it is a duplicate of #69.

**Closed by michaelwillis** 2020-04-27 00:07 UTC
