### ISSUE TITLE
Dry Level doesn't work on Room and Hall reverbs in 3.1.1

### ISSUE THREAD

**Issue by tassyv** [michaelwillis/dragonfly-reverb#77] opened 2020-06-14 07:29 UTC
Using the Linux 3.1.1 builds
I was surprised to only hear the reflections when using the Room or Hall Reverbs.
It's like Dry Level = 0 no matter the position of the fader (which does nothing)

The Plate and EarlyReflection reverbs behave correctly though.

I reverted to the 3.0.0 build and everything works as expected.

(Using the LV2 plugins in Ardour 5.12 on Fedora 31)

**Comment by trebmuh** [comment] 2020-06-14 14:32
If that can helps, I can't reproduce that here with 3.1.1 on LibraZiK-3 (LZK package).

**Comment by tassyv** [comment] 2020-06-14 17:18
I first noticed it using the rpm packages from Fedora copr (ycollet/linuxmao) but same issue with the compiled binaries straight from this git repo.
I'll try the stand-alone version in case this is somewhat tied to ardour but as explained, the 3.0.0 works fine :-/

**Comment by trebmuh** [comment] 2020-06-14 17:24
Did you tried in different hosts?

Also, I'm pinging Yann here: @ycollet

**Comment by tassyv** [comment] 2020-06-15 06:20
Well, I just tried the stand alone applications which I manually connected in Jack using the patchbay and using an  External Send in Ardour and this version works.
I also tried the VST versions and these also work.
But I confirm the LV2 versions of both the Hall and Room reverbs show the issue (Plate and EarlyReflection are OK)

**Comment by michaelwillis** [comment] 2020-06-16 20:56
@tassyv Thanks for reporting the bug, I don't know when I'll have time to work on it, but I did confirm the problem exists in the LV2 plugins, but not the VST plugins. Also, only Hall and Room mix two different reverb algorithms, so it must be a problem with that.

@trebmuh Are you using the LV2 plugins or the VST plugins?

**Comment by tassyv** [comment] 2020-06-17 05:53
Thanks for the update Michael.
Nothing urgent for me as I'm generally using these plugins on Aux Buses; so not using the Dry signal anyway ;-)
Thanks for these great reverbs by the way !!!

**Comment by trebmuh** [comment] 2020-06-18 01:16
@michaelwillis I've tried to reproduce with the LV2 version of the Hall and Room reverbs (didn't tried the others). After a bit of more digging, here is the outcomes:

- ardour6: I can reproduce the bug
- qtractor 0.9.14: I can't reproduce the bug
- jalv.select 1.3 (jalv.gtk) (jalv is 1.6.0~dfsg0-2): I can't reproduce the bug

**Comment by ChessboardRecords** [comment] 2020-06-21 16:49
The best reverbs they sound amazing

**Comment by xard-dev** [comment] 2020-06-25 18:05
Hello,

I can also confirm that 3.1.1 lv2 Room and Hall reverb dry is not working in Ardour 6.0. New **Plate** and **Early Reflection** plugins do work even in Ardour 6.0.

Tested the same LV2 3.1.1 plugins in Carla 2.1.0 and the dry works there as expected.

Previously I was using older 2.0.0 LV2 plugins and those work under Ardour 6.0 as expected.

**Comment by michaelwillis** [comment] 2020-06-25 19:28
@xard-dev Thanks. Until I fix this bug, release 3.0.0 should work for you:

https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.0.0

**Comment by xard-dev** [comment] 2020-06-27 08:13
@michaelwillis Thanks for the tip!

I Tried the 3.0.0 release and both LV2 Room and Hall reverb plugins work without the dry mix issue with Ardour 6.

And due to the modular design and being able to manually choose which versions to use for which plugin I could keep Plate and Early Reflection plugins at 3.1.1 level so that gives quite nice flexibility compared to monolithic all-or-nothing approach.

**Comment by michaelwillis** [comment] 2020-06-27 21:06
@tassyv @xard-dev I made a new release 3.1.2 that should fix this bug, please verify.

**Comment by trebmuh** [comment] 2020-06-27 21:46
It looks to be fixed on Ardour6 here. 3.1.2 is now on LibraZiK-3's repository.

**Comment by xard-dev** [comment] 2020-06-27 22:32
@michaelwillis I confirm that the 3.1.2 LV2 release fixed the dry mix bug in Hall and Room plugins when used with Ardour 6.

Single instance and multiple instances of both plugins were tested and found working.

**Closed** 2020-06-27 22:46 UTC

**Comment by tassyv** [comment] 2020-07-03 15:10
Just for the record, confirming it's also working fine in Ardour 5.12
Thanks !
