### ISSUE TITLE
text rendered at wrong size

### ISSUE THREAD

**Issue by rghvdberg** [michaelwillis/dragonfly-reverb#6] opened 2018-03-09 06:37 UTC
see #5

**Comment by michaelwillis** [comment] 2018-03-09 15:51
I think the problem is that the code is hardwired to look for the font in a specific place:

```
  fNanoFont  = fNanoText.createFontFromFile ( "lcd_solid","/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf" );
```

Not everybody is going to have the Noto Sans font there, in which case I think it defaults to some other font. We would probably have the best luck making it use a font that gets compiled in. It looks like DPF already compiles in Deja Vu Sans, so we could try that.

**Comment by rghvdberg** [comment] 2018-03-09 22:06
Gonna try moving the font in the source tree and make a relative path to the font. I tried that before on the old UI, but failed. Then I got lazy and just used a full path.

**Comment by michaelwillis** [comment] 2018-03-09 22:28
If all else fails, you can use Deja Vu Sans the same way that Distrho MVerb does it: https://github.com/DISTRHO/MVerb/blob/master/plugins/MVerb/DistrhoUIMVerb.cpp#L36

**Comment by rghvdberg** [comment] 2018-03-09 22:48
Yup, I know.
I'll look into it tomorrow.

**Comment by rghvdberg** [comment] 2018-03-10 09:04
Found it:
Indeed dpf falls back to Deja Vu Sans when it can't find the font. (I wish it would just give a compile error :-/ )
I don't think a relative path to font will work , so we need to have it compiled in.
The Deja Vu Sans font is here -> `dragonfly-reverb/dpf/dgl/src/Resources.hpp`
@falkTX seem to have used a util to auto-generate this file and we need that one.

**Comment by rghvdberg** [comment] 2018-03-10 10:07
latest PR should fix this :-)
please confirm

**Comment by michaelwillis** [comment] 2018-03-11 02:49
Fixed by d63efd36af0cd535cde3cd3e1d838e0b9e802f52

**Closed by michaelwillis** 2018-03-11 02:49 UTC
