### ISSUE TITLE
GUI Size Wrong - macOS 10.15.7 Studio One Pro 5

### ISSUE THREAD

**Issue by cpsmusic** [michaelwillis/dragonfly-reverb#115] opened 2021-11-10 11:25 UTC
Hi,

There's a problem with the GUIs of all four plug-ins on macOS 10.15.7 in Studio One Pro 5. The GUI is about 1/4 of the size of the window and the mouse interaction corresponds to the size of the larger window, not the actual GUI.

The same problem was happening with the GVST plug-ins which were fixed relatively quickly. Maybe contact the developer to find out what the problem was.

<img width="466" alt="Screen Shot 2021-11-10 at 10 23 52 pm" src="https://user-images.githubusercontent.com/6424857/141104739-65648067-b1f5-4268-a489-f8fe59391795.png">

**Comment by falkTX** [comment] 2021-11-10 12:05
We know what the problem is, and already already been fixed in the underlying framework.
Should be easily fixed by updating DPF and making a new release, whenever @michaelwillis (the author) has some time for it.

**Comment by michaelwillis** [comment] 2021-12-28 05:58
@falkTX Which branch of DPF should I use? The `.github/workflows/build.yml` file that you contributed refers to `dpf/utils/valgrind-dpf.supp`. From what I can tell, the valgrind suppressions are only available on the `develop` branch of DPF.

**Comment by falkTX** [comment] 2021-12-28 12:02
the develop branch for now.
once I am done with the vst3 stuff I will merge develop into master, but can take a bit still

**Comment by michaelwillis** [comment] 2022-03-31 04:08
@cpsmusic Please try the new [release v3.2.6](https://github.com/michaelwillis/dragonfly-reverb/releases/tag/3.2.6).

**Comment by michaelwillis** [comment] 2022-03-31 16:33
I'm closing this issue per the [comment on the 3.2.6 release discussion](https://github.com/michaelwillis/dragonfly-reverb/discussions/127#discussioncomment-2475185). I'm considering scaling up for high DPI to be a new feature request, and @falkTX has given me some direction on how to implement it, so that should be done in the next release.

**Closed by michaelwillis** 2022-03-31 16:33 UTC
